### PR TITLE
feat: use const generics instead of typenum

### PR DESCRIPTION
**Pull request by dignifiedquire**
Unfortunately defaults are not stable for const generics yet, but everything else just worked.

### CODE REVIEW

**Comment by storojs72** [comment]
@dignifiedquire, It seems that this work is a bit stale (last activity was 4 months ago). Probably we can close this PR for now if you don't have plans to return to this work. WDYT?

**Comment by dignifiedquire** [comment]
So rust 1.59 just added defaults for const generics, happy to update the PR if folks are interested in pursuing this

**Comment by cryptonemo** [comment]
> So rust 1.59 just added defaults for const generics, happy to update the PR if folks are interested in pursuing this

If you have the cycles to spare, it would be appreciated!  I'd like to have something to test compat with existing proofs to see exactly what we're dealing with, as I know we're also dealing with working with other deps these days that use const generics.

**Comment by storojs72** [comment]
With merging https://github.com/filecoin-project/merkletree/pull/97, https://github.com/filecoin-project/merkletree/pull/99 and https://github.com/filecoin-project/merkletree/pull/100, I see that this PR has some merge conflicts. I think that it is better to close it and reopen once again if necessary taking fresh `master` as a base. I'm not going to remove the branch

**Pull request closed without merging**
