### PR TITLE
security: change dep memmap -> memmap2

### PR DESCRIPTION
**Pull request by jiangying000**
memmap is unmaintained :
https://rustsec.org/advisories/RUSTSEC-2020-0077.html

### CODE REVIEW

**Comment by vmx** [comment]
@dignifiedquire Due to this issue I found https://github.com/filecoin-project/mapr, where the only real change is [feat: add support for lock and private on nix based systems ](https://github.com/filecoin-project/mapr/commit/628f7d1562d8b4e62882b00987b2efdbd09c4548). Upstreaming that to [memmap2](https://github.com/RazrFalcon/memmap2-rs) would make the `mapr` fork obsolete. Do you have time to upstream it?

**Comment by storojs72** [comment]
I support the approach of preferring maintainable dependencies. However, we use [mapr](https://github.com/filecoin-project/mapr) (which is a fork of [mammap](https://github.com/danburkert/memmap-rs)), mentioned by @vmx, at higher level - in [storage-proofs-porep](https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-porep/Cargo.toml#L17). Considering that mapr is maintained by our organisation, I would prefer using it here in merkletree crate and throughout other our crates, thereby reducing overall number of dependencies.

**Comment by dignifiedquire** [comment]
I don't have time to work on the upstream, but it would be great if things could be upstreamed and we don't have to maintain a separate crate.

**Comment by jiangying000** [comment]
> I don't have time to work on the upstream, but it would be great if things could be upstreamed and we don't have to maintain a separate crate.

Should I change dep in this pr to memmap2 ?

**Comment by vmx** [comment]
> I don't have time to work on the upstream, but it would be great if things could be upstreamed and we don't have to maintain a separate crate.

Thanks for the quick reply. I've opened https://github.com/filecoin-project/rust-fil-proofs/issues/1622 as tracking issue (as `mapr` doesn't have issues enabled). I'll try to get it upstreamed.

**Comment by storojs72** [comment]
I think, we can upstream mapr by recreating its repository, forking from memmap2 and manually adding @dignifiedquire's commits there. As we rely on functionality introduced in mapr ([mlock](https://github.com/filecoin-project/rust-fil-proofs/blob/master/storage-proofs-porep/src/stacked/vanilla/memory_handling.rs#L286) for instance) - it will also require updating mapr dependency in rust-fil-proofs, since I expect that we will need to publish new mapr version after "reforking" it. @vmx do you have similar thoughts or something different?

**Comment by vmx** [comment]
@storojs72 I'd keep `mapr` as it currently is and try to properly upstream things to `memmap2`. If things are accepted, we switch to `memmap2` in `rust-fil-proofs`. If it's not accepted, we can fast-forward `mapr` to the patched version and do a new release.

**Comment by storojs72** [comment]
> I'd keep mapr as it currently is and try to properly upstream things to memmap2. If things are accepted, we switch to memmap2 in rust-fil-proofs. If it's not accepted, we can fast-forward mapr to the patched version and do a new release.

Yeah, agree. Thanks! So let's hold on this RP, until we will know what dependency to use actually.

**Comment by storojs72** [comment]
Looks like https://github.com/RazrFalcon/memmap2-rs/pull/52 has been accepted and merged, so we should now have everything to finish this work, e.g. `memmap2` can be used throughout our codebase (here in context of current PR and in [rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs/tree/master/filecoin-proofs) as a separate PR there) instead of `memmap` / `mapr`. cc @jiangying000

**Comment by jiangying000** [comment]
@storojs72 thanks for reminding, I've made the change, but CI seems stucked, PTAL

**Review by storojs72 — APPROVED** [review]
Thanks, @jiangying000! I have manually run all tests and they are successful, so let me try to sort out with merging

**Review by cryptonemo — APPROVED** [review]

**Pull request merged**
